### PR TITLE
Rotate slope for y comparison

### LINKED ISSUE #465: Weird combination results
Howdy!

I'm using this excellent lib to generate keyboard layouts, but combining (unioning) shapes only seemed to work on one side, not the other. Attached is a fairly reduced JSON example of the expected behaviour and the error as well (the objects are the same, only the bad is mirrored and translated a bit).
[makerjs_debug.zip](https://github.com/microsoft/maker.js/files/4739963/makerjs_debug.zip)

The error happens when trying to combine the `a` and `b` parts of the models like so:

```
const json = <read json>
const combined = makerjs.model.combineUnion(json.models.a, json.models.b)
```

Everything is fine for the "good" input, while the result of the "bad" seemingly disappears.
After making sure that it's not due to my code, I rolled up my sleeves and went deep.
Turns out that the disappearance is because a line is incorrectly left out, and all the rest is then discarded as "dead ends".
It all leads back to `isSlopeEqual` is `equal.ts`, where both the slopes and the yIntercepts are checked to be within .00001 of each other.
The problem is that while slopes are always on the same scale, the differences of the yIntercepts can vary drastically with distance from the axis. So even if the slopes are well within .00001 of each other, the intercepts might not be after a certain distance.

[My very simplistic, quick&dirty fix](https://github.com/mrzealot/maker.js/commit/c41ac58590765f033139f8e18464976521de7c08) was to scale the yIntercept comparisons to a constant range, thereby making it independent of position.
Wdyt about this addition? Should I open a pull request or would another solution be more fitting long-term?

### PR DESCRIPTION
**Pull request by danmarshall**
@mrzealot - based on your issue, I had the idea to do a rotate translation of slopes so that the slope is flat, and we can compare the y components easily.

Fixes #465

### CODE REVIEW

**Comment by mrzealot** [comment]
@danmarshall Cool! Seems like a very elegant solution to handle the scale differences by rotation instead of manual scaling. I do wonder, tho, why the precision needs to change to `.000000001` in the test while it remains `.00001` in the code? I'm not sure I'm 100% clear on the underlying math, to be quite honest, but I recall my so-called "equal" slopes already differing in the 6th significant digit, thereby needing the original precision. Did my tests pass and you just *wanted* to change the test precision, or did you **need** to change it so the test would pass? If it's the latter, then I'm not sure it solves my original issue...

**Comment by danmarshall** [comment]
The change was required to pass [this condition](https://github.com/microsoft/maker.js/blob/59d0e6e76863f627d82677f727612b732545bed7/packages/maker.js/src/core/equal.ts#L189):
```js
 if (!isSlopeParallel(slopeA, slopeB)) return false;
```
This code executes and exits the function before the new code is reached.

**Comment by mrzealot** [comment]
So my tests didn't pass for you in their original form? Sorry if I'm being dense, but they did pass for me, and I think that they *should* pass for the new implementation, too (without the need to descrease the slope difference).

Also, if my tests fail: which assert fails at the parallel check already? Both? I should probably set this repo up sometime to re-check...

**Comment by danmarshall** [comment]
Sorry, it looks like they did pass the parallel test. looking into it...

**Comment by danmarshall** [comment]
@mrzealot - I may be running out of ideas. When 2 lines are non-parallel, the further from their intersection, the greater the difference between them. The only thing my new code did was measure the distance between them (if they were parallel and non angled). Whereas the previous code measured the distance between y intercept and angled). So I do like the new code addition, but it is actually increasing the precision, where you are looking for decreased precision in this case. Perhaps we should just add the precision as an option then?

**Comment by mrzealot** [comment]
Right, this is probably where I didn't fully get the math, then... What I see, tho, is that simply adding a precision parameter is not enough in itself, exactly because of the translation issue shown in the new test. If two lines are considered equal (within precision), then they should also be considered equal when translated further away.

Not to knock the rotation approach, but I don't see why a manual scaling is not appropriate here? At least, that's the only solution I see that would work. Maybe not by the `yIntercept` field (on second thought) as that could happen to be close to zero even while the lines are far away. But some distance from the y axis should play a role here. For example, if the `yIntercept`s of two lines are not equal, then they must have a valid intersection, whose distance we can then measure (and scale!) from the y axis.

**Comment by danmarshall** [comment]
> If two lines are considered equal (within precision), then they should also be considered equal when translated further away.

Actually, that's not the case. If they aren't perfectly parallel, as in these "approximate" tests, then the further away from their intersection, the further they are from each other. 
Also, taking the inversion:
```js
 factor = 1 / slopeA.yIntercept
```
means that as the y intercept becomes larger, the factor becomes smaller, which does not reflect that they *should* be further away.

**Comment by mrzealot** [comment]
> Actually, that's not the case. If they aren't perfectly parallel, as in these "approximate" tests, then the further away from their intersection, the further they are from each other.

What you probably mean is that the distance would get larger between them if we took segments from the same lines at points further away from their intersection. That would be correct indeed, no arguments there. What I meant, however, was that **when translated** (meaning that their intersection moves as well), their distance shouldn't matter from the y axis. If there is a position where they're considered equal (or, at least, within precison), then their arbitrarily translated versions should also be considered equal.

This all depends on what's our POV when deciding equality. In the general case, no amount of precision makes sense because if two slopes are not *exactly* equal, then there's a distance from the y axis for every d in R after which the distance between the lines is greater than d. This is not practically usable, tho, so there's a need for precision, of course. But this helps to reframe the problem. What we need, I think, is a parametric origin; a viewpoint. It was implicitly assumed that the origin is - well - the origin at [0, 0]. But this causes translation to return different equality results for the same pair of slopes, so it's not good enough.

But a viewpoint could help a lot. And any other function using `isSlopeEqual` could give it "hints" about where the difference should be evaluated. Because if we get to line **segments**, they're not just slopes anymore, and can give their center points or whatever as context. The safest bet is to also make the precision parametric, so that we can get context-independent equality by passing in zero.
Wdyt?

**Comment by danmarshall** [comment]
Hi @mrzealot - I think we're thinking the same way. I was hoping that by normalizing the slopes, by rotating to zero, that this would have found that "POV", or at least removed one dimension from the problem. Perhaps we can rotate endpoints of each line, instead of the y-intercept. Now we are only dealing with one dimension, so we can compare the y value of each point within the x-interval of each other's segment. If they aren't near or overlapping each other, we default to this original y intercept point. Hopefully that makes sense.

**Comment by mrzealot** [comment]
Oh nevermind, I just took a look at the `ISlope` interface, and realized that it already has access to the line it was calculated from! This makes everything so much easier. So yes, I agree with your method: rotating by one of the endpoints (per segment) and then seeing if the maximum absolute `y` difference (based on both sets of endpoints) is within precision of zero. Should solve the distance issue while not requiring any extra params. I like it.

**Comment by mrzealot** [comment]
Hi @danmarshall! Just checking in to ask about the status of this PR. Any idea if/when this gets merged? Anything further I can help with, maybe? :slightly_smiling_face:

**Comment by danmarshall** [comment]
Hi @mrzealot , I just got a few security advisories (finally) addressed today, so now I can get back to features like this. Sorry it took a long time to respond. I hope to get to this soon.

**Comment by danmarshall** [comment]
@mrzealot you have the patience of a saint :) I've finally got to making these changes.

**Comment by mrzealot** [comment]
Hey @danmarshall ! Thanks a bunch for following up on this! To be perfectly honest, my "saintly" patience is due mostly to having my own fork and depending on that for the time being, so I could "forget about this" in good conscience until now... :smile: But great to hear that I *should* be able to depend on an official release again.

Just to be sure: you're saying that this change solves **both** my issues (so the weird combinations results from #465 as well as this slope comparison)? If so, I'll need to retest, and hopefully change my dependency to a fresh official commit! :tada:

**Comment by danmarshall** [comment]
It may be possible that #465 isn't fixed, I wouldn't be surprised. If so, please reopen it. It was auto closed from the initial comment in this PR.

**Comment by muhaaas** [comment]
Been following #465 for a while since I had my own combination cases that resulted in similar artifacts. Glad to know that this library is still being patched years later.

**Pull request merged**
