### PR TITLE
Fix degenerate arc issue

### PR DESCRIPTION
**Pull request by eflynch**

### CODE REVIEW

**Comment by eflynch** [comment]
@microsoft-github-policy-service agree

**Comment by eflynch** [comment]
I checked locally that the unit test fails without the bug fix code change, so it is successfully testing the issue

**Comment by danmarshall** [comment]
Thanks for the contribution! I'm wondering if we should put the guard on the svg import code. 🤔

**Comment by eflynch** [comment]
I’m not sure quite what you mean, but if it’s helpful for evaluating what to do here, the reason I needed this change is because I need to round trip a makerjs model through an svg path, and depending on the exact situation, makerjs produces a model that holds these degenerate arcs which it was exporting successfully and then failing on import.

**Comment by danmarshall** [comment]
I see. If possible, a repro of that degeneration might be helpful.

**Comment by danmarshall** [comment]
Thanks! Published 0.18.1

**Pull request merged**
